name: Assemble

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Changelog
      run: git log --raw --no-merges --all > src/usr/share/doc/egg/changelog.Debian

    - name: Assemble w/ Make
      run: make clean assemble

    - uses: actions/upload-artifact@v4
      with:
        name: dump
        path: egg-v*.deb
